IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 320 # 320
  ROI_HEIGHT: 50  # 50

XYCAR:
  START_SPEED: 0.0
  MAX_SPEED: 20.0 # 15.0
  MIN_SPEED: 7.0 # 5.0
  SPEED_CONTROL_THRESHOLD: 15.0 # 15.0
  ACCELERATION_STEP: 0.15 # 0.05
  DECELERATION_STEP: 0.35  # 0.1

PID:
  P_GAIN: 0.125  # 0.20
  I_GAIN: 0.0006  # 0.0006
  D_GAIN: 0.08  # 0.08

STANLEY:
  K_GAIN: 0.032 # 0.032
  LOOK_AHEAD_DISTANCE: 0.2 # 0.2

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 25 # 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

CANNY:
  LOW_THRESHOLD: 200  # 200
  HIGH_THRESHOLD: 250 # 250

HOUGH:
  ABS_SLOPE_RANGE: 5.0  # 5.0
  THRESHOLD: 45 # 45
  MIN_LINE_LENGTH: 40 # 40
  MAX_LINE_GAP: 10  # 10

DEBUG: true
